contact_links:
  - name: LiveTL Discord
    url: https://discord.gg/BVpdvt7weG
    about: Not sure how to use the extension? Not sure if something is a bug? Just want to get some simple tech support? Join our discord server and ask your burning questions in the #bug-reports channel.
