name: Latest Release Build
on:
  release:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Package extensions
        run: make EMBED_DOMAIN=https://kentonishi.github.io/LiveTL/embed VERSION=$(echo -n ${{ github.ref }} | sed 's/[refs\/tagv]//g') all
      - name: Set gradle version
        run: make android-release EMBED_DOMAIN=https://kentonishi.github.io/LiveTL/embed VERSION=$(echo -n ${{ github.ref }} | sed 's/[refs\/tagv]//g')
      - name: Upload Chrome package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/chrome/LiveTL.zip
          asset_name: LiveTL-Chrome.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Firefox package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/firefox/LiveTL.zip
          asset_name: LiveTL-Firefox.zip
          tag: ${{ github.ref }}
          overwrite: true
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build release APK
        run: |
          cd LiveTL-Android
          bash ./gradlew assemble
          cd ..
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: LiveTL-Android/app/build/outputs/app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
      - name: Upload Android APK to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.sign_app.outputs.signedReleaseFile }}
          asset_name: LiveTL-Android.apk
          tag: ${{ github.ref }}
          overwrite: true
